import assert from "node:assert/strict";
import test from "node:test";

import { persona } from "../src/persona.mjs";

test("standing persona uses engagement-only windows and deliberate response placement", () => {
  const prompt = persona();
  const firstCapacityCheck = prompt.indexOf("At the start of every work turn, your first tool call is getManagedSessionCapacity");
  const acknowledgement = prompt.indexOf("send a one-line Slack acknowledgement before the first paid call");
  const firstPrice = prompt.indexOf("read its live catalog and price");
  assert.ok(firstCapacityCheck >= 0 && acknowledgement > firstCapacityCheck && firstPrice > acknowledgement);
  assert.match(prompt, /At the start of every work turn, your first tool call is getManagedSessionCapacity from the mounted Alder session-capacity reader/);
  assert.match(prompt, /Do not price, discover, or spend before you assess activeSegment\.actionableRemaining and the live-derived activeSegment\.resizeThreshold/);
  assert.match(prompt, /Window allowance, windowConsumed, reservedForActiveWork, and availableForNewAdmission are distinct facts/);
  assert.match(prompt, /Maintain the Services-surfaced resize threshold throughout work/);
  assert.match(prompt, /activeSegment\.minimumNextWindowAllowance/);
  assert.match(prompt, /windowAllowance is aggregate, not an increment/);
  assert.match(prompt, /Never work the window to zero/);
  assert.match(prompt, /Before posting completion or returning idle after substantial work, re-check the named managed-session engagement/);
  assert.match(prompt, /record its exact activeSegment\.actionableRemaining, activeSegment\.resizeThreshold, and activeSegment\.minimumNextWindowAllowance/);
  assert.match(prompt, /never report an allowance, cycle allocation, or parent-window value as remaining capacity/);
  assert.match(prompt, /The owner establishes the payment relationship and the agent may only increase its own managed-session usage window/);
  assert.match(prompt, /The only Services MCP capabilities mounted here are managed-session capacity inspection and deliberate managed-session increases/);
  assert.match(prompt, /The owner establishes this agent's first payment relationship during launch/);
  assert.match(prompt, /The agent cannot create a first payment grant/);
  assert.match(prompt, /Services POST \/connections\/recover/);
  assert.match(prompt, /store the returned sat_ access token only in the sandbox \.env/);
  assert.match(prompt, /The token authenticates to Services only/);
  assert.match(prompt, /createMerchantConnectionRecoveryProof for the existing Alder Services pma_/);
  assert.match(prompt, /one-use prp_ only in its dedicated header to Services POST \/connections\/recover/);
  assert.match(prompt, /never estimate rates from memory/);
  assert.match(prompt, /multi-step paid work.*send a one-line Slack acknowledgement before the first paid call/);
  assert.match(prompt, /estimate the total against activeSegment\.actionableRemaining while preserving activeSegment\.resizeThreshold/);
  assert.match(prompt, /record the estimate, reference-class basis, actionable remaining, resize threshold, and decision in \/provi\/active-work\.md/);
  assert.match(prompt, /deliberately use setUsageWindow to set that same managed-session engagement to the displayed absolute allowance/);
  assert.doesNotMatch(prompt, /twice its current windowAllowance/);
  assert.match(prompt, /a single durable rollover is already pending: do not issue another resize/);
  assert.match(prompt, /use its receipt endpoint for the actual captured amount/);
  assert.match(prompt, /Never ask a Slack participant for a supplier project ID/);
  assert.match(prompt, /never report it as "\$0 charged", create a second charge, or substitute a new idempotency key/);
  assert.match(prompt, /report reconciliation_pending with its exact cause, payment reference or hold reference, and financial state/);
  assert.match(prompt, /never report it as "\$0 charged"/);
  assert.doesNotMatch(prompt, /cumulative Services window/);
  assert.match(prompt, /If actionable remaining is at or below it, obtain activeSegment\.minimumNextWindowAllowance and deliberately set the engagement to that absolute target while the session can still reply/);
  assert.doesNotMatch(prompt, /create a payment grant/);
  assert.match(prompt, /reply top-level by omitting thread_ts/);
  assert.match(prompt, /agent\.message is internal session output and is never shown in Slack/);
  assert.match(prompt, /use the mounted Slack MCP server's message-sending tool/);
  assert.match(prompt, /confirm that the Slack MCP send succeeded/);
  assert.match(prompt, /A direct mention always earns a response/);
  assert.match(prompt, /#general channel and direct conversations/);
  assert.match(prompt, /root #general mention/);
  assert.match(prompt, /attention=ambient means you may read the message but ordinarily stay silent/);
  assert.match(prompt, /\/provi\/active-work\.md/);
  assert.match(prompt, /full provider health check cost \$2\.45 against a \$0\.60 default managed-session window/);
  assert.match(prompt, /After every costed task, record its verified total, the comparable work shape, and its receipt or payment reference in \/provi\/lessons\.md/);
  assert.match(prompt, /never poll, schedule work, watch typing/);
  assert.doesNotMatch(prompt, /\bProVI\b/);
  assert.doesNotMatch(prompt, /\b[CDTU]_[A-Z0-9]+\b/);
});
