import assert from "node:assert/strict";
import test from "node:test";

import { persona } from "../src/persona.mjs";

test("standing persona uses engagement-only windows and deliberate response placement", () => {
  const prompt = persona();
  const firstCapacityCheck = prompt.indexOf("Before meaningful Services work, and again before returning idle after substantial work, read your usage window through Services");
  const acknowledgement = prompt.indexOf("send a one-line Slack acknowledgement before the first paid call");
  assert.ok(firstCapacityCheck >= 0 && acknowledgement >= 0);
  assert.match(prompt, /How your Alder Services access works/);
  assert.match(prompt, /Your owner set up your payment relationship with Alder Services before you ever ran/);
  assert.match(prompt, /Sign in through recovery instead/);
  assert.match(prompt, /Alder MCP credential to list your existing merchant connection and mint a one-use recovery proof/);
  assert.match(prompt, /X-Alder-Connection-Recovery-Proof/);
  assert.match(prompt, /Do not put the proof in Authorization, Basic auth, a URL, or the JSON body/);
  assert.match(prompt, /Keep both proof and token out of Slack, memory, logs, and shell output/);
  assert.match(prompt, /write only the sat_ to your sandbox \.env/);
  assert.match(prompt, /use it for all Services calls: catalog, pricing, receipts, capacity reads, and provider operations/);
  assert.match(prompt, /Before meaningful Services work, and again before returning idle after substantial work, read your usage window through Services/);
  assert.match(prompt, /Your access token only proves who you are\. It cannot spend/);
  assert.match(prompt, /Window allowance, windowConsumed, reservedForActiveWork, availableForNewAdmission, and activeSegment\.actionableRemaining are distinct facts/);
  assert.match(prompt, /only actionableRemaining is spendable capacity/);
  assert.match(prompt, /Services reports these facts and does not choose your runway/);
  assert.match(prompt, /If that plan does not fit within actionableRemaining, choose and request a concrete absolute allowance that does fit/);
  assert.match(prompt, /The requested amount is your judgment from the work, not a Services recommendation/);
  assert.match(prompt, /An acknowledgement-only event asks only for acknowledgement/);
  assert.match(prompt, /with capacity remaining, acknowledge it without resizing or narrating capacity/);
  assert.match(prompt, /A request for substantive work remains substantive when it also asks for an acknowledgement: acknowledge first, then complete the requested work/);
  assert.match(prompt, /Same connection, same payment relationship, no new setup, ever/);
  assert.match(prompt, /Never attempt to create a wallet, a grant, or a payment relationship/);
  assert.match(prompt, /19408080000 at scale 9 is \$19\.40808, not \$19\.408B/);
  assert.match(prompt, /multi-step paid work.*send a one-line Slack acknowledgement before the first paid call/);
  assert.match(prompt, /record the estimate, reference-class basis, actionable remaining, requested allowance when one is needed, and decision in \/provi\/active-work\.md/);
  assert.match(prompt, /managed-session model, cache, output, and runtime price components/);
  assert.match(prompt, /provider route price alone is not the cost of completing hosted work/);
  assert.match(prompt, /Before the first paid call, record the estimate/);
  assert.match(prompt, /read GET \/receipts\/\{receiptRef\} with your access token/);
  assert.match(prompt, /a receipt reference in a response header is not the receipt itself/);
  assert.match(prompt, /Never ask a Slack participant for a supplier project ID/);
  assert.match(prompt, /never report it as "\$0 charged", create a second charge, or substitute a new idempotency key/);
  assert.match(prompt, /report reconciliation_pending with its exact cause, payment reference or hold reference, and financial state/);
  assert.match(prompt, /never report it as "\$0 charged"/);
  assert.doesNotMatch(prompt, /cumulative Services window/);
  assert.doesNotMatch(prompt, /controlReserve|resizeThreshold|minimumNextWindowAllowance|control_reserve/);
  assert.doesNotMatch(prompt, /getManagedSessionCapacity|setUsageWindow|alder-session-capacity/);
  assert.doesNotMatch(prompt, /Alder Core/);
  assert.match(prompt, /reply top-level by omitting thread_ts/);
  assert.match(prompt, /agent\.message is internal session output and is never shown in Slack/);
  assert.match(prompt, /use the mounted Slack MCP server's message-sending tool/);
  assert.match(prompt, /confirm that the Slack MCP send succeeded/);
  assert.match(prompt, /A direct mention always earns a response/);
  assert.match(prompt, /#general channel and direct conversations/);
  assert.match(prompt, /root #general mention/);
  assert.match(prompt, /attention=ambient means you may read the message but ordinarily stay silent/);
  assert.match(prompt, /\/provi\/active-work\.md/);
  assert.match(prompt, /full provider health check cost \$2\.45 against a \$0\.60 default managed-session window/);
  assert.match(prompt, /After every costed task, record its verified total, the comparable work shape, and its receipt or payment reference in \/provi\/lessons\.md/);
  assert.match(prompt, /never poll, schedule work, watch typing/);
  assert.doesNotMatch(prompt, /\bProVI\b/);
  assert.doesNotMatch(prompt, /\b[CDTU]_[A-Z0-9]+\b/);
});
